# Generated by Django 6.1 on 2026-09-05 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0005_wrongquestion_next_review_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('user', 'paper'), name='unique_active_exam_per_paper'),
        ),
    ]
