# Generated by Django 6.1 on 2026-09-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_examattempt_unique_active_exam_per_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceprogress',
            name='scope',
            field=models.CharField(max_length=150),
        ),
    ]
